# docker-compose.yml
version: '3.8'
services:
  mcnc-rag-assistant:
    build: .
    container_name: mcnc-rag-assistant
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - chromadb

  chromadb:
    image: chromadb/chroma:latest
    container_name: mcnc-chromadb
    ports:
      - "8000:8000"
    volumes:
      - ./data/chromadb:/chroma/chroma