# .github/workflows/manual-parsing.yml
name: Manual Document Parsing

on:
  workflow_dispatch:
    inputs:
      parse_all:
        description: '모든 문서 재파싱'
        type: boolean
        default: false
      specific_path:
        description: '특정 경로만 파싱 (선택사항)'
        type: string
        required: false

# 권한 설정 추가
permissions:
  contents: write  # 파일 읽기/쓰기 권한
  actions: read    # Actions 읽기 권한

jobs:
  parse:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # 토큰 설정 추가 (더 안전한 방법)
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0  # 전체 히스토리 가져오기

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          pip install PyMuPDF python-docx python-pptx pandas openpyxl

      - name: Parse documents
        run: |
          if [ "${{ inputs.parse_all }}" = "true" ]; then
            echo "모든 문서 파싱 중..."
            python scripts/batch_parser.py --all
          elif [ -n "${{ inputs.specific_path }}" ]; then
            echo "특정 경로 파싱: ${{ inputs.specific_path }}"
            python scripts/batch_parser.py "${{ inputs.specific_path }}"
          else
            echo "새로 추가된 파일 파싱 중..."
            python scripts/batch_parser.py --new-only
          fi

      - name: Commit results
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Parsed documents [skip ci]'
          file_pattern: 'data/processed/**'
          # 추가 설정
          commit_user_name: github-actions[bot]
          commit_user_email: 41898282+github-actions[bot]@users.noreply.github.com
          commit_author: GitHub Actions <actions@github.com>
          skip_dirty_check: false
          skip_fetch: false